const BRAND_ALIASES: Record<string, string> = {
  'vw': 'Volkswagen',
  'volkswagen': 'Volkswagen',
  'bmw': 'BMW',
  'mercedes': 'Mercedes-Benz',
  'mercedes-benz': 'Mercedes-Benz',
  'peugeot': 'Peugeot',
  'peugot': 'Peugeot',
  'peagout': 'Peugeot',
  'citroen': 'Citroën',
  'citroën': 'Citroën',
  'renault': 'Renault',
  'opel': 'Opel',
  'ford': 'Ford',
  'audi': 'Audi',
  'seat': 'SEAT',
  'skoda': 'Škoda',
  'škoda': 'Škoda',
  'toyota': 'Toyota',
  'honda': 'Honda',
  'hyundai': 'Hyundai',
  'kia': 'Kia',
  'nissan': 'Nissan',
  'mazda': 'Mazda',
  'fiat': 'Fiat',
  'alfa': 'Alfa Romeo',
  'volvo': 'Volvo',
  'mini': 'MINI',
  'jeep': 'Jeep',
  'dacia': 'Dacia',
  'tesla': 'Tesla',
  'jaguar': 'Jaguar',
  'porsche': 'Porsche',
  'lexus': 'Lexus',
  'subaru': 'Subaru',
  'suzuki': 'Suzuki',
  'mitsubishi': 'Mitsubishi',
  'landrover': 'Land Rover',
  'land rover': 'Land Rover',
}

export function normalizeBrand(brand: string): string {
  const key = brand.toLowerCase().trim()
  return BRAND_ALIASES[key] ?? brand.charAt(0).toUpperCase() + brand.slice(1).toLowerCase()
}
